// <auto-generated />
using ApiPiedraPapelTijera.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiPiedraPapelTijera.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210210030923_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiPiedraPapelTijera.Models.Jugador", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("ApiPiedraPapelTijera.Models.Partida", b =>
                {
                    b.Property<int>("Idpartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IdJugador1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdJugador2")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MovimientoJ1")
                        .HasColumnType("int");

                    b.Property<int>("MovimientoJ2")
                        .HasColumnType("int");

                    b.HasKey("Idpartida");

                    b.HasIndex("IdJugador2");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("ApiPiedraPapelTijera.Models.Partida", b =>
                {
                    b.HasOne("ApiPiedraPapelTijera.Models.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("IdJugador2");
                });
#pragma warning restore 612, 618
        }
    }
}
