// <auto-generated />
using System;
using ApiPiedraPapelTijera.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiPiedraPapelTijera.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiPiedraPapelTijera.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("ApiPiedraPapelTijera.Models.Partida", b =>
                {
                    b.Property<int>("Idpartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdJugador1")
                        .HasColumnType("int");

                    b.Property<int>("IdJugador2")
                        .HasColumnType("int");

                    b.HasKey("Idpartida");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("ApiPiedraPapelTijera.Models.Ronda", b =>
                {
                    b.Property<int>("IdRonda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ganador")
                        .HasColumnType("int");

                    b.Property<int>("Idpartida")
                        .HasColumnType("int");

                    b.Property<int>("MovimientoJ1")
                        .HasColumnType("int");

                    b.Property<int>("MovimientoJ2")
                        .HasColumnType("int");

                    b.HasKey("IdRonda");

                    b.HasIndex("Idpartida");

                    b.ToTable("Ronda");
                });

            modelBuilder.Entity("ApiPiedraPapelTijera.Models.Ronda", b =>
                {
                    b.HasOne("ApiPiedraPapelTijera.Models.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("Idpartida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
